# Spotify Automation Configuration - Intelligent Geo-Matching
# System automatically detects proxy location and matches appropriate User-Agent, language, timezone

# Test Account Configuration
accounts:
  - email: .....
    password: ......
    proxy: 192.168.100.1:2112

# Example Account Configuration
example_accounts:
  - email: user1@example.com
    password: pass123
    proxy: us-pr.smartproxy.com:8080:username1:password1  # US proxy
  - email: user2@example.com
    password: pass456
    proxy: uk-pr.smartproxy.com:8080:username2:password2  # UK proxy
  - email: user3@example.com
    password: pass789
    proxy: de-pr.smartproxy.com:8080:username3:password3  # DE proxy

# Geographic Proxy Pool Configuration - System auto-detects location and matches settings
proxies:
  # Test proxy - Local network proxy
  - host: 192.168.100.1
    port: 2112
    username: ""  # Fill in username if proxy requires authentication
    password: ""  # Fill in password if proxy requires authentication
    type: http
    location: DEFAULT

  # Example proxy configurations
  # US proxy - Auto-matches: en-US language, US timezone, USD currency
  - host: us-pr.smartproxy.com
    port: 8080
    username: username1
    password: password1
    type: http
    location: US  # Optional: manually specify location

  # UK proxy - Auto-matches: en-GB language, London timezone, GBP currency
  - host: uk-pr.smartproxy.com
    port: 8080
    username: username3
    password: password3
    type: http

  - host: london.proxyservice.com
    port: 8080
    username: username4
    password: password4
    type: http

  # DE proxy - Auto-matches: de-DE language, Berlin timezone, EUR currency
  - host: de-pr.smartproxy.com
    port: 8080
    username: username5
    password: password5
    type: http

  - host: germany.proxyservice.com
    port: 1080
    username: username6
    password: password6
    type: socks5

  # CA proxy - Auto-matches: en-CA/fr-CA language, Canada timezone, CAD currency
  - host: ca-pr.smartproxy.com
    port: 8080
    username: username7
    password: password7
    type: http

  # AU proxy - Auto-matches: en-AU language, Australia timezone, AUD currency
  - host: au-pr.smartproxy.com
    port: 8080
    username: username8
    password: password8
    type: http

# Playback Configuration
playback:
  songs:
    - "https://open.spotify.com/track/0docDTO7aMbzz3vOkQfSTc"
  repeat_count: [2, 3]  # Repeat play count range
  play_duration: [110, 120]  # Play duration range (seconds)
  session_delay: [5, 10]  # Delay between sessions (seconds)

# Anti-Detection Configuration
stealth:
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  screen_sizes:
    - [1920, 1080]
    - [1366, 768]
    - [1440, 900]
  languages: ["en-US", "en-GB", "en-HK"]
  timezones: ["America/New_York", "Europe/London", "Asia/Hong_Kong"]
