# Behavior patterns for Spotify automation

# Skip patterns define how long to listen to a track before potentially skipping.
# - duration: Base listening time in seconds.
# - jitter: Random variation (± seconds) to apply to the base duration.
# - weight: Probability weight for selecting this pattern. Higher means more likely.
skip_patterns:
  short: { duration: 40, jitter: 5, weight: 0.4 }
  medium: { duration: 55, jitter: 5, weight: 0.4 }
  long: { duration: 180, jitter: 5, weight: 0.2 }
  # Example of an even shorter pattern, e.g., for ads or very quick skips
  # very_short: { duration: 15, jitter: 3, weight: 0.1 }

# Pause patterns define natural breaks between actions or tracks.
# - min: Minimum pause duration in seconds.
# - max: Maximum pause duration in seconds.
# - weight: Probability weight for selecting this pause type.
pause_patterns:
  quick: { min: 1, max: 3, weight: 0.3 }
  normal: { min: 3, max: 8, weight: 0.5 }
  long: { min: 8, max: 15, weight: 0.2 }
  # Example of a very short "thinking time" pause
  # micro: { min: 0.5, max: 1.5, weight: 0.1 }

# Session lengths define overall session duration parameters.
# Not directly used in the current BehaviorEngine methods but planned for future use.
# - tracks: Array [min_tracks, max_tracks] to play in a session.
# - duration: Array [min_duration_seconds, max_duration_seconds] for the session.
session_lengths:
  short: { tracks: [1, 3], duration: [60, 180] }       # 1-3 minutes
  medium: { tracks: [3, 8], duration: [180, 480] }     # 3-8 minutes
  long: { tracks: [8, 15], duration: [480, 900] }      # 8-15 minutes
  # extended: { tracks: [15, 30], duration: [900, 1800] } # 15-30 minutes

# Other potential behavior configurations:
# like_probability: 0.05  # Chance to "like" a song
# follow_artist_probability: 0.02 # Chance to follow an artist
# search_variation_enabled: true # Whether to vary search terms slightly
# human_interaction_events: # Probabilities for various UI interactions
#   scroll_page: { probability: 0.6, frequency: 'per_track_change' }
#   mouse_move_randomly: { probability: 0.8, frequency: 'periodic', interval_seconds: 10 }
#   navigate_to_artist_page: { probability: 0.1, after_tracks_played: 5 }
#   explore_playlist: { probability: 0.15, after_session_start_seconds: 300 }
