# Shift scheduling configurations for Spotify Automation Farm

# Defines different operational shifts, their timing, and capacity.
# - name: Descriptive name for the shift.
# - start_hour: The hour (0-23) when the shift begins (inclusive).
# - end_hour: The hour (0-23) when the shift ends (exclusive).
#   - If end_hour < start_hour, the shift is assumed to cross midnight.
# - capacity: Percentage (0.0 to 1.0) of maxSessions to run during this shift.
# - timezone: Timezone for interpreting start_hour and end_hour (e.g., "UTC", "America/New_York").
#             If not specified, system's local timezone or UTC might be assumed by node-cron.
# - cronPattern: Specific cron pattern for starting this shift. Used by node-cron.
shifts:
  morning:
    name: "Morning Shift"
    start_hour: 6
    end_hour: 12
    capacity: 0.3
    timezone: "UTC"
    cronPattern: "0 6 * * *"
  afternoon:
    name: "Afternoon Shift"
    start_hour: 12
    end_hour: 18
    capacity: 1.0 # 100% capacity
    timezone: "UTC"
    cronPattern: "0 12 * * *"
  night:
    name: "Night Shift"
    start_hour: 18
    end_hour: 6 # Crosses midnight, ends at 6 AM the next day
    capacity: 0.5
    timezone: "UTC"
    cronPattern: "0 18 * * *"
  # Example of a weekend-specific shift (would require more complex getCurrentShift logic for name matching)
  # weekend_peak:
  #   name: "Weekend Peak"
  #   start_hour: 10
  #   end_hour: 16
  #   capacity: 0.8
  #   timezone: "America/Los_Angeles"
  #   cronPattern: "0 10 * * 6,0" # 10 AM on Sat and Sun

# Configuration for transitions between shifts.
transition:
  # Duration in minutes over which capacity changes should be spread when a shift changes.
  duration_minutes: 30

  # Whether to implement gradual scaling during the transition period.
  gradual_scaling: true # Placeholder for future use

  # Whether a brief overlap in shift capacities is allowed during transition.
  overlap_allowed: true # Placeholder for future use
